# https://scrutinizer-ci.com/docs/configuration/build_reference
# https://scrutinizer-ci.com/docs/tools/external-code-coverage/

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - "docs/"
        - "tests/"

tools:
    external_code_coverage: true
